name: androidversion
description: Get android version code and name.
version: 0.0.1
homepage: https://github.com/emekalites/flutter_android_version

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0  <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.emekalites.androidversion
        pluginClass: AndroidVersionPlugin
